function daq = initDAQ()

daq = struct(...
             'active',[],...   
             'name','',...
             'subName','',...
             'path',struct('base','','data',''),... 
             'readable',[],...
             'rAccess',struct('active',[],'IP','','user','','fileExt','','remotePath','','port',''),...
             'lAccess',struct('active',[],'fileExt','','path','','zip',[]),...
             'unpacking',struct('path',struct('base','','rawData','','rawDataDat','','rawDataMat',''),'fileExt','','bufferSize','','type','','keepHLDs','','writeTDCCal',[]),...
             'raw2var',struct('path',struct('base','','varData','','lookUpTables',''),'lookUpTables','','keepRawFiles',[]),...
             'var2cal',struct('path',struct('base','','calData','','lookUpTables',''),'lookUpTables','','keepVarFiles',[]),...
             'out',struct(),...
             'TRB3',struct('active',[],'type','','centralFPGA','','FPGAs',[]),...    
             'TRB2',struct('active',[])...    
             );               
return


