#!/usr/bin/env bash
set -euo pipefail
shopt -s nullglob

show_help() {
  cat <<'EOF'
clean_temps.sh
Removes temporary and "removed" files generated by the STAGE_0 unpacker.

Usage:
  clean_temps.sh

Options:
  -h, --help    Show this help message and exit.

The script deletes temporary, removed, and done artefacts from both the active
DATAFLOW_v3 tree and the SAFE_DATAFLOW_v3 mirror. Run it only when no unpacker
jobs are in progress.
EOF
}

if [[ ${1:-} =~ ^(-h|--help)$ ]]; then
  show_help
  exit 0
fi

TARGETS=(
  "$HOME/DATAFLOW_v3/MASTER/STAGE_0/UNPACKER_ZERO_STAGE_FILES/system/devices/TRB3/data/daqData/varData/tmp_mi0*"
  "$HOME/SAFE_DATAFLOW_v3/MASTER/STAGE_0/UNPACKER_ZERO_STAGE_FILES/system/devices/TRB3/data/daqData/varData/tmp_mi0*"
  "$HOME/DATAFLOW_v3/MASTER/STAGE_0/UNPACKER_ZERO_STAGE_FILES/system/devices/TRB3/data/daqData/rawData/dat/removed/*"
  "$HOME/SAFE_DATAFLOW_v3/MASTER/STAGE_0/UNPACKER_ZERO_STAGE_FILES/system/devices/TRB3/data/daqData/rawData/dat/removed/*"
  "$HOME/DATAFLOW_v3/MASTER/STAGE_0/UNPACKER_ZERO_STAGE_FILES/system/devices/TRB3/data/daqData/asci/removed/*"
  "$HOME/SAFE_DATAFLOW_v3/MASTER/STAGE_0/UNPACKER_ZERO_STAGE_FILES/system/devices/TRB3/data/daqData/asci/removed/*"
  "$HOME/DATAFLOW_v3/MASTER/STAGE_0/UNPACKER_ZERO_STAGE_FILES/system/devices/TRB3/data/daqData/varData/*"
  "$HOME/SAFE_DATAFLOW_v3/MASTER/STAGE_0/UNPACKER_ZERO_STAGE_FILES/system/devices/TRB3/data/daqData/varData/*"
  "$HOME/DATAFLOW_v3/MASTER/STAGE_0/UNPACKER_ZERO_STAGE_FILES/system/devices/TRB3/data/daqData/rawData/dat/done/*"
  "$HOME/SAFE_DATAFLOW_v3/MASTER/STAGE_0/UNPACKER_ZERO_STAGE_FILES/system/devices/TRB3/data/daqData/rawData/dat/done/*"
)

for pattern in "${TARGETS[@]}"; do
  rm -rf $pattern
done
