              %Column
              %varName
              %devName
              %devsubNam
              %Alarm active
              %Alarm active, mim value for alarm
              %Alarm active, max value for alarm
distributionLookUpTable = {...
                       1,          2,          3,          4,         11,         12;...
                  'IHVp',     'IHVn',     'VHVn',     'VHVp',  'InLimit',  'IpLimit';... 
             'SELADA1M2','SELADA1M2','SELADA1M2','SELADA1M2','SELADA1M2','SELADA1M2';...
                     '' ,         '',         '',         '',         '',         '';...
                   {0,0},      {0,0},      {0,5},      {0,5},    {0,0.5},    {0,0.5};...
                 {0,0.5},    {0,0.5},    {0,5.8},    {0,5.8},    {0,0.0},   {0,0.0}};
