         %Column
         %varName
         %devName
         %devsubNam
         %Alarm active, min value for alarm, needed amout of repetitions needed to trigger
         %Alarm active, max value for alarm, needed amout of repetitions needed to trigger
         %Action active, min value for action, needed amout of repetitions needed to trigger, action
         %Action active, max value for action, needed amout of repetitions needed to trigger, action
distributionLookUpTable = {...
                       1,          2,          3;...
                'Disk01',   'Disk02',     'File';...
                 'DAQ01',    'DAQ01',    'DAQ01';...
                     '' ,         '',         '';...
                 {0,0,0},    {0,0,0}, {1,1000,1};...
                {1,80,1},   {1,80,1},   {0,90,0};...
              {0,0,0,''}, {0,0,0,''}, {0,0,0,''};...
              {0,0,0,''}, {0,0,0,''}, {0,0,0,''}};
