              %Column
              %varName
              %devName
              %devsubNam
              %Alarm active
              %Alarm active, mim value for alarm
              %Alarm active, max value for alarm
distributionLookUpTable = {...
                       1,          2,         3,          4,          5,          6,          7,          8;...
                'TEMP01',   'TEMP02',  'TEMP03',   'TEMP04',     'HR01',     'HR02',  'Press01',  'Press02';...
             'SELADA1M2','SELADA1M2','SELADA1M2','SELADA1M2','SELADA1M2','SELADA1M2','SELADA1M2','SELADA1M2';...
                     '' ,        '' ,       '' ,        '' ,         '',         '',         '',         '';...
                   {0,0},      {0,0},     {0,0},      {0,0},      {0,5},      {0,5},    {0,0.5},    {0,0.5};...
                 {0,0.5},    {0,0.5},   {0,0.5},    {0,0.5},    {0,5.8},    {0,5.8},    {0,0.0},   {0,0.0}};
