# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# GLOBAL
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

home_path: "/home/mingo"


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# ANCILLARY
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# METADATA PLOTTER (metadata_plotter.py)
new_just_to_check: 0

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# FIRST STAGE
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# FIRST_STAGE - LAB_LOGS (log_bring_and_clean.sh)
# -----------------------------------------------------------------------------

create_new_csv: true

outlier_limits:
  rates_Asserted: [0, 60]
  rates_Edge: [0, 45]
  rates_Accepted: [0, 30]
  rates_Multiplexer1: [0, 400]
  rates_M2: [0, 400]
  rates_M3: [0, 400]
  rates_M4: [0, 400]
  rates_CM1: [0, 30]
  rates_CM2: [0, 30]
  rates_CM3: [0, 30]
  rates_CM4: [0, 30]
  sensors_ext_Temperature_ext: [0, 50]
  sensors_ext_RH_ext: [0, 100]
  sensors_ext_Pressure_ext: [500, 1300]
  sensors_int_Temperature_int: [0, 100]
  sensors_int_RH_int: [0, 100]
  sensors_int_Pressure_int: [500, 1300]
  odroid_DiskFill1: [0, 100]
  odroid_DiskFill2: [0, 100]
  odroid_DiskFillX: [0, 100000]
  flow_FlowRate1: [0, 1500]
  flow_FlowRate2: [0, 1500]
  flow_FlowRate3: [0, 1500]
  flow_FlowRate4: [0, 1500]
  hv_HVneg: [-0.1, 20]
  hv_HVpos: [-0.1, 20]


# -----------------------------------------------------------------------------
# FIRST_STAGE - COPERNICUS (copernicus.py)
# -----------------------------------------------------------------------------

test_mode: false
weeks_behind_requested: 1
max_weeks_allowed: 2  # Maximum admitted by CDS is 21, but this is faster
degree_apotema: 0.25


# -----------------------------------------------------------------------------
# EVENT_DATA
# -----------------------------------------------------------------------------

# FIRST_STAGE - EVENT_DATA - BRING (bring_data_and_config_files.sh)

logbook:
  sheet_id: "1ato36QkIXCxFkDT_LtAaLjPP7pvLcor-xZAP4fy00l0"
  gid_by_station:
    "1": 1331842924
    "2": 600987525
    "3": 376764978
    "4": 1268265225


# -----------------------------------------------------------------------------
# FIRST_STAGE - EVENT_DATA - RAW_TO_LIST (raw_to_list_events.sh)
# -----------------------------------------------------------------------------

stratos_save: true
fast_mode: false # Do not iterate TimTrack, neither save figures, etc.
debug_mode: false # Only 10000 rows with all detail
last_file_test: false
alternative_fitting: true

not_use_q_semisum_for_slew_corr: true

residue_plots: false


# -----------------------------------------------------------------------------
# Execution options -----------------------------------------------------------
# -----------------------------------------------------------------------------

# Plots and savings -------------------------
crontab_execution: true
create_plots: false
create_essential_plots: false
create_very_essential_plots: false
save_plots: false
show_plots: false
create_pdf: false
limit: false
limit_number: 10000
number_of_time_cal_figures: 3
save_calibrations: true
# save_full_data: false
presentation: false
presentation_plots: false
force_replacement: false # Creates a new datafile even if there is already one that looks complete
article_format: false

# Charge calibration to fC -------------------------
calibrate_charge_ns_to_fc: true

# Charge front-back --------------------------------
charge_front_back: true

# Slewing correction -------------------------------
slewing_correction: true

# Time filtering -----------------------------------
time_window_filtering: true

# Time calibration ---------------------------------
time_calibration: true
old_timing_method: false
brute_force_analysis_time_calibration_path_finding: false

# Y position ---------------------------------------
y_position_complex_method: false
uniform_y_method: true
uniform_weighted_method: false

# RPC variables ------------------------------------
y_new_method: true
blur_y: true

# Alternative --------------------------------------
alternative_iteration: false
number_of_alt_executions: 2

# TimTrack -----------------------------------------
fixed_speed: false
res_ana_removing_planes: true
timtrack_iteration: false
number_of_TT_executions: 1

validate_charge_pedestal_calibration: true

EXPECTED_COLUMNS_config: 71

residual_plots: false
residual_plots_fast: false
residual_plots_debug: false

timtrack_iteration: true
timtrack_iteration_fast: false
timtrack_iteration_debug: false

time_calibration: true
time_calibration_fast: false
time_calibration_debug: false

charge_front_back: true
charge_front_back_fast: false
charge_front_back_debug: false

create_plots: false
create_plots_fast: false
create_plots_debug: true

limit: false
limit_fast: false
limit_debug: true

limit_number: None
limit_number_fast: 10000
limit_number_debug: 10000

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Filters ---------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# General ---------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Pre-cal Front & Back --------------------------------------------------------
# -----------------------------------------------------------------------------

T_side_left_pre_cal_debug: -500
T_side_right_pre_cal_debug: 500
Q_side_left_pre_cal_debug: -500
Q_side_right_pre_cal_debug: 500

T_side_left_pre_cal_default: -200  #-130
T_side_right_pre_cal_default: -100
Q_side_left_pre_cal_default: 80
Q_side_right_pre_cal_default: 300

T_side_left_pre_cal_ST: -200  #-115
T_side_right_pre_cal_ST: -50
Q_side_left_pre_cal_ST: 80
Q_side_right_pre_cal_ST: 300

# -----------------------------------------------------------------------------
# Pre-cal Sum & Diff ----------------------------------------------------------
# -----------------------------------------------------------------------------
# Qsum
Q_left_pre_cal: 75
Q_right_pre_cal: 500
# Qdif
Q_diff_pre_cal_threshold: 20
# Tsum
T_sum_left_pre_cal: -200 # was -130 for mingo01 but for mingo03 is different
T_sum_right_pre_cal: -90

# Tdif
T_diff_pre_cal_threshold: 20

# -----------------------------------------------------------------------------
# Post-calibration ------------------------------------------------------------
# -----------------------------------------------------------------------------
# Qsum
Q_sum_left_cal: -20
Q_sum_right_cal: 300
# Qdif
Q_diff_cal_threshold: 10
Q_diff_cal_threshold_FB: 2 # 1.25
Q_diff_cal_threshold_FB_wide: 10 # In case the fitting fails
# Tsum
T_sum_left_cal: -5
T_sum_right_cal: 5
# Tdif
T_diff_cal_threshold: 1

# -----------------------------------------------------------------------------
# Once calculated the RPC variables -------------------------------------------
# -----------------------------------------------------------------------------
# Tsum
T_sum_RPC_left: -5
T_sum_RPC_right: 5 # -100
# Tdiff
T_diff_RPC_left: -0.8
T_diff_RPC_right: 0.8
# Qsum
Q_RPC_left: 0
Q_RPC_right: 500
# Qdiff
Q_dif_RPC_left: -4
Q_dif_RPC_right: 4
# Y pos
Y_RPC_left: -200 # -150
Y_RPC_right: 200 # 150

# -----------------------------------------------------------------------------
# Alternative fitter filter ---------------------------------------------------
# -----------------------------------------------------------------------------
alt_pos_filter: 650
alt_theta_left_filter: 0
alt_theta_right_filter: 1.5708 # np.pi/2
alt_phi_left_filter: -3.141592 # -1*np.pi
alt_phi_right_filter: 3.141592 # np.pi
alt_slowness_filter_left: -0.005
alt_slowness_filter_right: 0.01 # 0.025

alt_res_ystr_filter: 300
alt_res_tsum_filter: 2
alt_res_tdif_filter: 0.7

# -----------------------------------------------------------------------------
# TimTrack filter -------------------------------------------------------------
# -----------------------------------------------------------------------------
proj_filter: 2


res_ystr_filter: 300
res_tsum_filter: 2
res_tdif_filter: 0.7

ext_res_ystr_filter: 300
ext_res_tsum_filter: 2
ext_res_tdif_filter: 0.7

# -----------------------------------------------------------------------------
# Fitting comparison ----------------------------------------------------------
# -----------------------------------------------------------------------------
delta_s_left: -0.0003
delta_s_right: 0.0003

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Calibrations ----------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# Time sum
CRT_gaussian_fit_quantile: 0.03
coincidence_window_og_ns: 10  # ns
coincidence_window_precal_ns: 7  # ns
coincidence_window_cal_ns: 3  # ns
coincidence_window_cal_number_of_points: 20  # ns

# Pedestal charge calibration
pedestal_left: -3
pedestal_right: 2

# Front-back charge
distance_sum_charges_left_fit: -5
distance_sum_charges_right_fit: 200
distance_diff_charges_up_fit: 10
distance_diff_charges_low_fit: -10
distance_sum_charges_plot: 800
front_back_fit_threshold: 4 # It was 1.4

# -----------------------------------------------------------------------------
# Variables to modify ---------------------------------------------------------
# -----------------------------------------------------------------------------
beta: 1
strip_speed_factor_of_c: 0.666666667
validate_pos_cal: true

# Front-back charge
output_order: 0
degree_of_polynomial: 4

# X ---------------------------------------------------------------------------
strip_length: 300
narrow_strip: 63
wide_strip: 98


# Timtrack parameters --------------------
# Hardcoded
d0   : 10 # initial value of the convergence parameter
cocut: 1  # convergence cut: 0.1
iter_max: 10 # maximum number of iterations: 50
anc_sy: 25 # 2.5 cm
anc_sts: 0.35 # 400 ps
anc_std: 0.075
anc_sz: 10 # 5 cm

n_planes_timtrack: 4

# -----------------------------------------------------------------------------
# Plotting options ------------------------------------------------------------
# -----------------------------------------------------------------------------

T_clip_min_debug: -500
T_clip_max_debug: 500
Q_clip_min_debug: -500
Q_clip_max_debug: 500
num_bins_debug: 100  # Parameter for the number of bins

T_clip_min_default: -300
T_clip_max_default: 100
Q_clip_min_default: 0
Q_clip_max_default: 500
num_bins_default: 100  # Parameter for the number of bins

T_clip_min_ST: -300
T_clip_max_ST: 100
Q_clip_min_ST: 0
Q_clip_max_ST: 500

# New channel-wise plot -------------------------------------------------------
log_scale: true

calibrate_strip_Q_pedestal_thr_factor: 31.62
calibrate_strip_Q_pedestal_thr_factor_2: 1.5
calibrate_strip_Q_pedestal_translate_charge_cal: 0.25

calibrate_strip_Q_pedestal_percentile: 10

# 5% of the maximum count
calibrate_strip_Q_pedestal_rel_th: 0.015
calibrate_strip_Q_pedestal_rel_th_cal: 0.4
calibrate_strip_Q_pedestal_abs_th: 3
calibrate_strip_Q_pedestal_q_quantile: 0.4

scatter_2d_and_fit_new_xlim_left: -5
scatter_2d_and_fit_new_xlim_right: 200
scatter_2d_and_fit_new_ylim_bottom: -11
scatter_2d_and_fit_new_ylim_top: 11

calibrate_strip_T_diff_T_rel_th: 0.1
calibrate_strip_T_diff_T_abs_th: 1

interpolate_fast_charge_Q_clip_min: 0
interpolate_fast_charge_Q_clip_max: 1750
interpolate_fast_charge_num_bins: 100
interpolate_fast_charge_log_scale: true

crosstalk_fitting: true
delta_t_left: -5
delta_t_right: 5
q_sum_left: 0
q_sum_right: 60
q_diff_left: -40
q_diff_right: 40

Q_sum_semidiff_left: -10
Q_sum_semidiff_right: 10
Q_sum_semisum_left: 10
Q_sum_semisum_right: 50
T_sum_corrected_diff_left: -5
T_sum_corrected_diff_right: 5
slewing_residual_range: 5

t_comparison_lim: 4
t0_time_cal_lim: 10

crosstalk_fit_mu_max: 3 # 1.5
crosstalk_fit_sigma_min: 0.25
crosstalk_fit_sigma_max: 1

slewing_correction_r2_threshold: 0.2

time_window_fitting: true

charge_plot_limit_left: 0
charge_plot_limit_right: 100
charge_plot_event_limit_right: 400






# -----------------------------------------------------------------------------
# FIRST_STAGE - EVENT_DATA - EVENT_ACCUMULATOR (ev_accumulator.sh)
# -----------------------------------------------------------------------------

# General settings
correct_angle: false
last_file_test: false
update_big_event_file: false

multiple_files: true

run_jupyter_notebook: false

remove_outliers: true

# Plot settings
create_plots: false
create_essential_plots: false
create_very_essential_plots: false
save_plots: false
create_pdf: false
force_replacement: false  # Creates a new datafile even if there is already one that looks complete
show_plots: false

# Angular region selection
theta_boundaries:
  - 5
  - 15
  - 25
region_layout:
  - 1
  - 8
  - 8
  - 8

# Particular analysis
side_calculations: true
eff_vs_charge: true
eff_vs_angle_and_pos: true
noise_vs_angle: false
noise_2d: true
charge_vs_angle: false
polya_fit: true
real_strip_case_study: false
multiplicity_calculations: true
crosstalk_probability: true
n_study_fit: false
topology_plots: false

# Configuration for multiple files in event_accumulator
cluster_of_files: 7  # Adjust as needed
time_window_in_hours: 10  # Time window in hours to look for files
time_tolerance_in_minutes: 10  # Tolerance in minutes for overlapping time ranges

three_plane_eff: false

# Limits
crosstalk_limit: 1
streamer_limit: 100

# Constants
q_e: 1.602e-4  # fC


blurring_angular: true
blurring_sigma_angular: 2

blurring_xy: false
blurring_sigma_xy: 0.05

draw_angular_regions: true
time_to_min: false




# FIRST_STAGE - EVENT_DATA - BIG EVENT FILE JOINER (big_event_file_joiner.py)

load_big_event_file: false
significant_digits: 6

suffixes: # These are the columns to average, the others are summing
  # Summary metrics and quality flags
  - CRT_avg
  - sigmoid_width
  - background_slope
  - one_side_events
  - purity_of_data_percentage
  - unc_y
  - unc_tsum
  - unc_tdif

  # Reconstruction outputs
  - x
  - y
  - theta
  - phi
  - s
  - th_chi
  - x_std
  - y_std
  - theta_std
  - phi_std
  - s_std
  - th_chi_std

  # Streamer fractions
  - streamer_percent_1
  - streamer_percent_2
  - streamer_percent_3
  - streamer_percent_4

  # Config
  - over_P1
  - P1-P2
  - P2-P3
  - P3-P4
  - phi_north



# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# SECOND STAGE
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------


# SECOND_STAGE - MERGE INTO LARGE TABLE

DECIMAL_PLACES: 2



# SECOND_STAGE - CORRECTOR

# -----------------------------------------------------------------------------
# Touch -----------------------------------------------------------------------
# -----------------------------------------------------------------------------

use_two_planes_too: false
date_selection: true  # Set to true if you want to filter by date
start_date_filter: "2025-01-01"
end_date_filter: "2025-12-31"

# Aesthetic -------------------------------------
show_plots: false
save_plots: true
create_plots: false
create_essential_plots: false
create_very_essential_plots: false
show_errorbar: false

# Execution -------------------------------------
only_all: true
recalculate_pressure_coeff: true
remove_outliers: true

rolling_effs: true
mean_window: 5
med_window: 3
rolling_mean: false
rolling_median: true

outlier_gaussian_quantile: 0.02 # 2%

res_win_min: 60 # 180 Resampling window minutes
HMF_ker: 3 # It must be odd. Horizontal Median Filter
MAF_ker: 0 # Moving Average Filter
acceptance_corr: false
high_order_correction: false


# -----------------------------------------------------------------------------
# To not touch unless necesary ------------------------------------------------
# -----------------------------------------------------------------------------

# This should come from an input file
eta_P: -0.162 # pressure_coeff_input
unc_eta_P: 0.013 # unc_pressure_coeff_input
set_a: -0.11357 # pressure_intercept_input
mean_pressure_used_for_the_fit: 940

low_lim_eff_plot: 0
systematic_unc:
  - 0
  - 0
  - 0
  - 0 # From simulation

systematic_unc_corr_to_real_rate: 0

remove_non_data_points: true
repeat_efficiency_calculation: true
decorrelate: true
fit_efficiencies: true
significant_digits: 4