function dev = initDevice()

dev = struct(...
               'active',[],...
               'name','',...
               'subName','',...
               'type','',...
               'subType','',...
               'reportable',struct('active',[],'LT','','timeElapsed',''),...
               'path',struct('base','','data',''),...
               'dcs',struct('active',[],'readable',[],...
                            'rAccess',struct('active',[],'IP','','port','','user','','key','','fileExt',[],'remotePath','','keepData','','zipData','','filesLeft',''),...
                            'lAccess',struct('active',[]),...
                            'dcData2MatScript','',...
                            'distributionLT','',...
                            'path',struct('base','','rawData','','rawDataDat','','rawDataMat','','data','','LT','')...
                            ),...
               'ana',struct('active',[],...  
                            'path',struct('base','')...
                            )...
             );               
return
