# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# GLOBAL
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

home_path: "/home/mingo"
config_files_directory: "/home/mingo/DATAFLOW_v3/MASTER/CONFIG_FILES"


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# ANCILLARY
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# METADATA PLOTTER (metadata_plotter.py)
new_just_to_check: 0

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# FIRST STAGE
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# STAGE_1 - LAB_LOGS (log_bring_and_clean.sh)
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

create_new_csv: true

outlier_limits:
  rates_Asserted: [0, 60]
  rates_Edge: [0, 45]
  rates_Accepted: [0, 30]
  rates_Multiplexer1: [0, 400]
  rates_M2: [0, 400]
  rates_M3: [0, 400]
  rates_M4: [0, 400]
  rates_CM1: [0, 30]
  rates_CM2: [0, 30]
  rates_CM3: [0, 30]
  rates_CM4: [0, 30]
  sensors_ext_Temperature_ext: [0, 50]
  sensors_ext_RH_ext: [0, 100]
  sensors_ext_Pressure_ext: [500, 1300]
  sensors_int_Temperature_int: [0, 100]
  sensors_int_RH_int: [0, 100]
  sensors_int_Pressure_int: [500, 1300]
  odroid_DiskFill1: [0, 100]
  odroid_DiskFill2: [0, 100]
  odroid_DiskFillX: [0, 100000]
  flow_FlowRate1: [0, 1500]
  flow_FlowRate2: [0, 1500]
  flow_FlowRate3: [0, 1500]
  flow_FlowRate4: [0, 1500]
  hv_HVneg: [-0.1, 20]
  hv_HVpos: [-0.1, 20]


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# STAGE_1 - COPERNICUS (copernicus.py)
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

test_mode: false
weeks_behind_requested: 1
max_weeks_allowed: 2  # Maximum admitted by CDS is 21, but this is faster
degree_apotema: 0.25


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# EVENT_DATA
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# STAGE_1 - EVENT_DATA - BRING (bring_data_and_config_files.sh)
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

logbook:
  sheet_id: "1ato36QkIXCxFkDT_LtAaLjPP7pvLcor-xZAP4fy00l0"
  gid_by_station:
    "1": 1331842924
    "2": 600987525
    "3": 376764978
    "4": 1268265225


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# STAGE_1 - EVENT_DATA - RAW_TO_LIST (raw_to_list_events.sh)
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

stratos_save: true
fast_mode: false # Do not iterate TimTrack, neither save figures, etc.
debug_mode: false # Only 10000 rows with all detail
last_file_test: false
alternative_fitting: true
not_use_q_semisum_for_slew_corr: true
residue_plots: false

# Plots and savings -------------------------
crontab_execution: true
limit: false
limit_number: 10000
number_of_time_cal_figures: 3
save_calibrations: true
# save_full_data: false
presentation: false
presentation_plots: false
force_replacement: false # Creates a new datafile even if there is already one that looks complete
article_format: false

calibrate_charge_ns_to_fc: true

# Charge front-back --------------------------------
charge_front_back: true

# Slewing correction -------------------------------
slewing_correction: false

# Time filtering -----------------------------------
time_window_filtering: false

# Time calibration ---------------------------------
time_calibration: true
old_timing_method: true
brute_force_analysis_time_calibration_path_finding: false

# Y position ---------------------------------------
y_position_complex_method: false
uniform_y_method: true
uniform_weighted_method: false

# RPC variables ------------------------------------
y_new_method: true
blur_y: true

# Alternative --------------------------------------
alternative_iteration: false
number_of_alt_executions: 2

# TimTrack -----------------------------------------
fixed_speed: false
res_ana_removing_planes: true
timtrack_iteration: false
number_of_TT_executions: 1

validate_charge_pedestal_calibration: true

EXPECTED_COLUMNS_config: 71

residual_plots: false
residual_plots_fast: false
residual_plots_debug: false

timtrack_iteration: true
timtrack_iteration_fast: false
timtrack_iteration_debug: false

time_calibration: true
time_calibration_fast: false
time_calibration_debug: false

charge_front_back: true
charge_front_back_fast: false
charge_front_back_debug: false

limit: false
limit_fast: false
limit_debug: true

limit_number: None
limit_number_fast: 10000
limit_number_debug: 10000


# ALL THE VARIABLES THAT WERE HERE ARE NOW IN THE PARAMETER CSV FILE
# ~/DATAFLOW_v3/MASTER/CONFIG_FILES/config_parameters.csv



# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# STAGE_1 - EVENT_DATA - EVENT_ACCUMULATOR (ev_accumulator.sh)
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# General settings
correct_angle: false
last_file_test: false
update_big_event_file: false

multiple_files: true
run_jupyter_notebook: false
remove_outliers: true

# Plot settings
create_plots: false
create_essential_plots: true
save_plots: true
create_pdf: true
force_replacement: true  # Creates a new datafile even if there is already one that looks complete
show_plots: false


# Particular analysis
side_calculations: true
eff_vs_charge: true
eff_vs_angle_and_pos: true
noise_vs_angle: false
noise_2d: true
charge_vs_angle: false
polya_fit: true
real_strip_case_study: false
multiplicity_calculations: true
crosstalk_probability: true
n_study_fit: false
topology_plots: false

# Configuration for multiple files in event_accumulator
cluster_of_files: 7  # Adjust as needed
time_window_in_hours: 10  # Time window in hours to look for files
time_tolerance_in_minutes: 10  # Tolerance in minutes for overlapping time ranges

three_plane_eff: false

# Limits
crosstalk_limit: 1
streamer_limit: 100

# Constants
q_e: 1.602e-4  # fC

blurring_angular: true
blurring_sigma_angular: 2

blurring_xy: false
blurring_sigma_xy: 0.05

draw_angular_regions: true
time_to_min: false


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# STAGE_1 - EVENT_DATA - BIG EVENT FILE JOINER (big_event_file_joiner.py)
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

load_big_event_file: false
significant_digits: 6

suffixes: # These are the columns to average, the others are summing
  # Summary metrics and quality flags
  - CRT_avg
  - sigmoid_width
  - background_slope
  - one_side_events
  - purity_of_data_percentage
  - unc_y
  - unc_tsum
  - unc_tdif

  # Reconstruction outputs
  - x
  - y
  - theta
  - phi
  - s
  - th_chi
  - x_std
  - y_std
  - theta_std
  - phi_std
  - s_std
  - th_chi_std

  # Streamer fractions
  - streamer_percent_1
  - streamer_percent_2
  - streamer_percent_3
  - streamer_percent_4

  # Config
  - over_P1
  - P1-P2
  - P2-P3
  - P3-P4
  - phi_north



# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# SECOND STAGE
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# STAGE_2 - MERGE INTO LARGE TABLE
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

DECIMAL_PLACES: 2


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# STAGE_2 - CORRECTOR
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Touch -----------------------------------------------------------------------
# -----------------------------------------------------------------------------

use_two_planes_too: false
date_selection: true  # Set to true if you want to filter by date
start_date_filter: "2025-01-01"
end_date_filter: "2025-12-31"

# Aesthetic -------------------------------------
show_errorbar: false

# Execution -------------------------------------
only_all: true
recalculate_pressure_coeff: true
remove_outliers: true

rolling_effs: true
mean_window: 5
med_window: 3
rolling_mean: false
rolling_median: true

outlier_gaussian_quantile: 0.02 # 2%

res_win_min: 60 # 180 Resampling window minutes
HMF_ker: 3 # It must be odd. Horizontal Median Filter
MAF_ker: 0 # Moving Average Filter
acceptance_corr: false
high_order_correction: false


# -----------------------------------------------------------------------------
# To not touch unless necesary ------------------------------------------------
# -----------------------------------------------------------------------------

# This should come from an input file
eta_P: -0.162 # pressure_coeff_input
unc_eta_P: 0.013 # unc_pressure_coeff_input
set_a: -0.11357 # pressure_intercept_input
mean_pressure_used_for_the_fit: 940

low_lim_eff_plot: 0
systematic_unc:
  - 0
  - 0
  - 0
  - 0 # From simulation

systematic_unc_corr_to_real_rate: 0

remove_non_data_points: true
repeat_efficiency_calculation: true
decorrelate: true
fit_efficiencies: true
significant_digits: 4
